<?php
	$this->title = '用户组管理 - 业务监控系统';
	$this->sideMenu = 'alert';
	$this->subMenu = 'alert_groups';
?>

<style type="text/css">
label{
	display: inline-block;
	float: left;
	font-weight: 600;
	cursor: auto;
	font-size: 12px;
	width: 150px;
	text-align: left;
}

.field-box {
	margin-bottom: 30px;
	margin-left: 0;
	float: left;
	width: 100%;
}
#config-back {
	margin-left:10px;
}

a {
	cursor:pointer;
}

</style>
<link href="/static/css/lib/select2.css" type="text/css" rel="stylesheet" />
<div class="container-fluid">
            <div id="pad-wrapper" class="form-page">
            	<h3>用户组管理-<?php if(isset($D['id'])) echo '编辑';else echo '新增';?></h3>
            	<hr/>
                <div class="row-fluid form-wrapper">
                    <!-- left column -->
                    <div class="span10 column">
                        <form id="monitor-config-form" class="form-horizontal" role="form" onsubmit="return SubmitForm(this);" />
                            <input type="hidden" id="id" value="<?php echo isset($D['id'])?$D['id']:'';?>" /> 
                                                        
                            <div class="field-box">
                                <label>用户组名称:</label>
                                <input id="groupname" class="span5 inline-input" value="<?php echo (isset($D['groupname']) AND $D['groupname']) ? $D['groupname']:'';?>" data-toggle="tooltip" data-trigger="focus" title="用户组名称" data-placement="right" type="text" />
                            </div>
                            
                            <div class="field-box">
                                <label>包含用户:</label>
                                <select style="width:250px" multiple="" id="user_id" class="select2">
                                    <option />
                                    <?php if($D['ouser']):?>
                                    <?php if(isset($D['user_id'])) $users = explode(',',$D['user_id']);?>
                                    <?php foreach($D['ouser'] as $user):?>
                                    	<option value="<?php echo $user['id']?>" 
                                    	<?php if(in_array($user['id'], $users)) echo 'selected="1"';?>
                                    	/><?php echo $user['fullname'].'-'.$user['aliasname'];?>
                                    <?php endforeach;?>
                                    <?php endif;?>
                                </select>
                            </div>
                            
                            <div class="field-box">
                                <label>备注:</label>
                                <textarea id="notify_other" class="span8" rows="4"><?php echo isset($D['notify_other'])?$D['notify_other']:'';?></textarea>
                            </div>
                            <button id="config-submit" type="button" class="btn btn-default btn-primary">提交</button>
                            <a id="config-back" href="/alert/groups">返回</a>
                        	<div id="tip_submit" class="alert alert-success" style="visibility:hidden;margin-top:10px;font-size:18px;"></div>
                        </form>
                        
                    </div>
					<!-- end form -->
                </div>
            </div>
        </div>
        
<div id="suc" title="" style="visibility:hidden;text-align:center;">
	<h3>提交成功！</h3>
	<span></span>
</div>        
<script src="/static/js/select2.min.js"></script>
<script type="text/javascript">
$(function () {

	// select2 plugin for select elements
    $(".select2").select2({
        placeholder: "Select a State"
    });

	
	$("#config-submit").click(function(){
		SubmitForm();
	});

	$("#monitor_test").click(function(){
		var testurl = $("#monitor_url").val();
		var testparam = $("#monitor_param").val().split('\n').join('&');
		$.ajax({
			url:testurl,
		    type:'get',
		    dataType: 'json',
		 	data: testparam,
		 	async: false,
		 	success: function(data){
			 	if(data.flag == 'success') {
			 		$("#monitor_result").html(JSON.stringify(data.data));
				} else if(data.flag == 'error') {
					$("#monitor_result").html(JSON.stringify(data.msg));
				} else {
					$("#monitor_result").html('Unknow error!');
				}
	       	}
		});
	});
	
});

function SubmitForm(obj) {
	var configData = {
			id				: $("#id").val(),
			groupname		: $("#groupname").val(),
			apps			: $("#apps").val(),
			hosts			: $("#host_id").val(),
            services		: $("#services").val(),
			keyword			: $("#keyword").val(),
			user_id			: $("#user_id").val(),
			notify_status	: $("#notify_status").val(),
			notify_method	: jqchk('notify_method'),
			notify_type		: jqchk('notify_type'),
			notify_period	: $("#notify_period").val(),
			notify_other	: $("#notify_other").val(),
            notify_relation_1	: $("#notify_relation_1").val(),
            notify_relation_2	: $("#notify_relation_2").val(),
			};
	//console.log(configData);
	//提交数据
	$.ajax({
		url:'/alert/groups?o=add',
	    type:'post',
	    dataType: 'json',
	 	data: configData,
	 	async: false,
	 	success: function(data){
            console.log(data.flag);
            $("#tip_submit").css('visibility','visible').attr('class','alert alert-'+data.flag).html(data.msg);
       	}
	});
}

function jqchk(name){  //jquery获取复选框值    
	  var chk_value =[];    
	  $('input[name="'+name+'"]:checked').each(function(){    
		  chk_value.push($(this).val());    
	  });    
	  return chk_value.length==0 ? '' : chk_value;   
}    
</script>