<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->title; ?></title>
    <meta charset=utf-8>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <!-- bootstrap -->
    <link href="/static/css/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="/static/css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
    <link href="/static/css/bootstrap/bootstrap-overrides.css" type="text/css" rel="stylesheet" />

    <link href="/static/css/lib/font-awesome.css" type="text/css" rel="stylesheet" />

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="/static/css/layout.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/elements.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/icons.css" />

    <!-- this page specific styles -->
    <link rel="stylesheet" href="/static/css/compiled/signin.css" type="text/css" media="screen" />
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <style type="text/css">
        .login-wrapper { top: 200px; }
        .navbar-inverse .brand { padding:10px 0px 0px 10px;}
        .navbar-inner { height: 46px; }
        .login-wrapper .action span {text-transform: uppercase;color: #7e91aa;font-weight: 600;display: inline-block;vertical-align: middle; margin: 0 2px 0 8px;}
        .login-wrapper .action input.reset {color: #7e91aa;font-weight: 500;}
    </style>
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/theme.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
<body>

    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <a href="/index" class="brand">
                <img src="/static/img/logo.png" class="logo" />
            </a>
        </div>
    </div>

    <?php echo $_content; ?>

    <input type="hidden" id="backPage" value="<?php echo User_Session::getBackPage(); ?>" />
    <script type="text/javascript" src="/static/js/noty/packaged/jquery.noty.packaged.min.js"></script>
    <script type="text/javascript" src="/static/js/sign.js"></script>
</body>
</html>