<?php
    $this->title = '登陆 - 业务监控系统';
?>
<div class="row-fluid login-wrapper">
    <div class="box">
        <div class="content-wrap">
            <h6>登陆</h6>
            <input class="span12" type="text" id="email" placeholder="邮箱地址" />
            <input class="span12" type="password" id="password" placeholder="密码" />
            <div class="action">
                <a class="btn btn-glow primary login" href="javascript:;" >登陆</a>
                <span>OR</span>
                <input type="reset" value="匿名" class="reset anonymous">
            </div>
        </div>
    </div>
</div>