<?php
$this->title = '访问次数 - 业务监控系统';
$this->sideMenu = 'statisticlist';
$this->subMenu = 'accessNumber';
$this->status = array(200, 403, 404, 499, 500, 502, 504, 505);

?>
<link href="/static/css/lib/select2.css" type="text/css" rel="stylesheet" />
<div class="container-fluid">
    <div id="pad-wrapper" class="users-list">
        <div class="row-fluid header">
            <h3>访问次数</h3>
            <div class="search span10 pull-right">
                <div class="form">
                    <input type="text" id="from_date"  onclick="WdatePicker({dateFmt:'yyyy-M-d',skin:'twoer'})" placeholder="日期">
                    <select multiple="" id="param_status" class="select2" style="min-height: 80px">
                        <?php foreach ($this->status AS $status) { ?>
                            <option value="<?php echo $status ?>"><?php echo $status ?></option>
                        <?php } ?>
                    </select>
                    <i class="spacing"></i>
                    <a class="btn-flat small" id="filter">筛选</a>
                </div>
            </div>
            <div class="search span10 pull-right">
                <div class="form">
                    <div class="btn-group">
                        <input type='hidden' class="btn glow node_text" data-value="" />
                    </div>
                </div>
            </div>
        </div>

        <!-- Users table -->
        <div class="row-fluid table">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="sortable">
                        <span class="line">主机</span>
                    </th>
                    <th class="sortable">
                        <span class="line">路径</span>
                    </th>
                    <th class="sortable">
                        <span class="line">状态</span>
                    </th>
                    <th class="sortable">
                        <span class="line">次数</span>
                    </th>
                </tr>
                </thead>
                <tbody class="list-body">
                    <tr>
                        <td colspan="11" style="text-align: center;"><img src="/static/images/ajax-loader.gif" /></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="pageNav" class="pagination pull-right">
        </div>
        <!-- end users table -->
</div>
<input type="hidden" id="page" value="1" />
<input type="hidden" id="page_num" value="" />
<input type="hidden" id="from_time" value="" />
<!--<input type="hidden" id="to_time" value="" />-->
<script src="/static/js/select2.min.js"></script>
<script type="text/javascript" src="/static/js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript">
    $(function(){
        $(".select2").select2({
            placeholder: "状态"
        });

        $('#pageNav').delegate('.prev_page', 'click', function(){
            var page = parseInt($('#page').val());
            var page_num = $('#page_num').val();
            var prev_page = page - 1;
            if(prev_page < 1) {
                prev_page = 1;
            }
            initList(prev_page);
        })

        $('#pageNav').delegate('.next_page', 'click', function(){
            var page = parseInt($('#page').val());
            var page_num = $('#page_num').val();
            var next_page = page + 1;
            if(next_page > page_num) {
                next_page = page_num;
            }
            initList(next_page);
        })

        $('#pageNav').delegate('.jump_page', 'click', function(){
            var page = parseInt($(this).data('page'));
            initList(page);
        })

        $('#filter').on('click', function() {
            var from_time = $('#from_date').val();
            $('#from_time').val(from_time);
            initList(1);
        })

        $('.choose_node').on('click', function() {
            var name = $(this).data('name');
            $('.node_text').html(name);
            $('.node_text').data("value", name);
        });
        var initList = function(page) {
            $('#page').val(page);
            var node = $('.node_text').data("value");
            var from = $('#from_time').val();
            var status = $('#param_status').val() ? $('#param_status').val() : '';

            var url = '/api/analytics/accessList?type=access&page='+ page;

            if(from.length > 0) {
                url += '&from='+ from;
            }

            if(node.length > 0) {
                url += '&collection='+ node;
            }

            if (status.length > 0) {
                url += '&status='+ status;
            }

            var host = decodeURIComponent(getCookie('USER_BUSINESS'));

            if(host.length > 0 && host != "undefined") {
                url += '&host=' + host;
            }

            $.ajax({
                url: url,
                dataType: 'json',
                success: function(result) {
                    var data  = result.data.data;
                    var page_num = result.data.count;
                    if(page_num > 0) {
                        $('#page_num').val(page_num);
                        var listBodyStr = '';
                        var i = 1;

                        $.each(data, function(i, n) {

                            if(i == 1) {
                                listBodyStr += '<tr class="first">';
                            } else {
                                listBodyStr += '<tr>';
                            }

                            listBodyStr += '<td><span title="'+ n.host         +'">'+ n.host                    +'</span></td>';
                            listBodyStr += '<td><span title="'+ n.path         +'">'+ n.path      +'</span></td>';
                            listBodyStr += '<td><span title="'+ n.status +'">'+ n.status            +'</span></td>';
                            listBodyStr += '<td><span title="'+ n.num         +'">'+ n.num                    +'</span></td>';
                            listBodyStr += '</tr>';
                            i++;
                        })
                        $('.list-body').html(listBodyStr);

                        if(page_num > 0){
                            var pageStr = '<ul><li><a href="javascript:;" class="prev_page">‹</a>';
                                pageStr += '<li><a class="jump_page" href="javascript:;"  data-page="1">首页</a></li>';

                            var show_page_num = 10;
                            var start_num = page;

                            if ((page_num - page) >= 10) {
                                show_page_num = page + 11;
                            } else {
                                show_page_num = page_num;
                            }

                            for(var i = start_num; i <= show_page_num; i++) {
                                if(page == i) {
                                    pageStr += '<li><a class="active jump_page" href="javascript:;"  data-page="'+ i +'">'+ i +'</a></li>';
                                } else {
                                    pageStr += '<li><a class="jump_page" href="javascript:;"  data-page="'+ i +'">'+ i +'</a></li>';
                                }
                            }
                            pageStr += '<li><a class="jump_page" href="javascript:;"  data-page="'+ page_num +'">尾页</a></li>';
                            pageStr += '<li><a href="javascript:;" class="next_page">›</a></li></ul>';
                            $('.pagination').html(pageStr);
                        } else {
                            $('.pagination').html("");
                        }

                    } else {
                        $('#from_time').val('');
                        $('#to_time').val('');
                        $('#from_date').val('');
                        $('#to_date').val('');
                        $('#from_date').focus();

                        var warning = noty({
                            text        : '没有数据！',
                            type        : 'warning',
                            dismissQueue: true,
                            layout      : 'topCenter'
                        });
                        $('.list-body').html('');
                        setTimeout(function() { warning.close() }, 5000);
                    }
                }
            })
        }

        initList(1);
    })
</script>