<?php
    $this->title = '监控设定 - 业务监控系统';
    $this->resources = 'monitor_setting';
    $this->currentDate = $this->date ? $this->date : date('Y-m-d');
?>
<style type="text/css">
    td{
        border: 1px solid #edf2f7;
    }
    .right {
        border-right:1px solid #B8B8B8;
    }
</style>
<div class="container-fluid">
    <div id="pad-wrapper">
        <div class="table-wrapper products-table">
            <div class="row-fluid head">
                <div class="span12">
                    <h4>监控设定</h4>
                </div>
            </div>
            <div class="row-fluid filter-block"></div>
            <div class="row-fluid">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th colspan="3" class="span3">
                            <input type="checkbox">全部选择
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="span2"></td>
                        <td>URL</td>
                        <td class="span2">状态</td>
                    </tr>
                    <tr>
                    <?php
                        foreach ($business AS $key => $value) {
                    ?>
                        <td>
                            <input type="checkbox" name="business" value="<?php echo $value['id'] ?>">
                        </td>
                        <td>
                            <?php echo $value['host'] ?>
                        </td>
                        <td>
                            <?php
                                if ($value['status'] === 'close') {
                                    echo '<span class="label">关闭</span>';
                                } else {
                                    echo '<span class="label label-success">开启</span>';
                                }
                            ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tr>
                    </tbody>
                </table>
                <input type="hidden" id="page" value="1" />
                <input type="hidden" id="page_num" value="" />
            </div>
            <div class="pull-right">(开启则选择，关闭则不选)
                <a class="btn-glow primary status_operate" data-status="open">设置</a>&nbsp;
                <!--<a class="btn-glow status_operate" data-status="close">关闭</a>-->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.status_operate').on('click', function() {
            var business = $('input[name="business"]:checked');
            var businessString = '';
            var status = $(this).data('status');


            for(var i = 0; i < business.length; i++) {
                businessString += business[i].value + ',';
            }

            businessString = businessString.substr(0, businessString.length - 1);

            var url = '/index/setting';
            var data = 'status='+ status +'&business=' + businessString;

            $.ajax({
                url: url,
                data: data,
                type: 'post',
                dataType: 'json',
                success: function(returns) {
                    if (returns.result == 'success') {
                        var message = noty({
                            text        : '操作成功！',
                            type        : 'information',
                            dismissQueue: true,
                            layout      : 'center'
                        });
                        setTimeout(function() { window.location.reload(); }, 2000);
                    } else {
                        var message = noty({
                            text        : '操作失败！',
                            type        : 'warning',
                            dismissQueue: true,
                            layout      : 'center'
                        });
                        setTimeout(function() { message.close() }, 2000);
                    }
                }
            })
        })
    })
</script>