# !/bin/sh
#拷贝app目录结构到需要的机器上
#   1. scp yaf目录结构到远端机器
#
##@author    changbo<prince.chang@yeahmobi.com>
#@date      2014-03-17
#@version   0.1.0
#运行环境app所在目录(目标机器app目录路径，所有的机器统一采用此规范路径)
YPP_PATH=/YeahMobi/ypp
110:
	scp -r ./conf/*  root@172.30.10.110:$(YPP_PATH)/app/yeahmobi/
